# Generated by Django 4.1.13 on 2023-11-18 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdata',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemdata',
            name='hdd_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemdata',
            name='ram_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
