# Generated by Django 4.1.13 on 2023-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_systemdata_cpu_usage_systemdata_hdd_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdata',
            name='ram_total',
            field=models.FloatField(default=0.0),
        ),
    ]
