# Generated by Django 4.1.13 on 2023-11-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_systemdata_ram_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdata',
            name='hdd_total',
            field=models.FloatField(default=0.0),
        ),
    ]
