# Generated by Django 4.1.13 on 2023-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemMonitoringData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ram_usage", models.FloatField()),
                ("cpu_usage", models.FloatField()),
                ("hdd_usage", models.FloatField()),
                ("network_requests", models.IntegerField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
