# Generated by Django 4.1.13 on 2023-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmonitoringdata',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='systemmonitoringdata',
            name='hdd_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='systemmonitoringdata',
            name='ram_usage',
            field=models.FloatField(default=0.0),
        ),
    ]
